# Generated by Django 2.1.7 on 2019-03-10 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20190304_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='bedroooms',
            new_name='bedrooms',
        ),
    ]
