# Generated by Django 2.1.7 on 2019-03-10 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20190310_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='bedroooms',
            new_name='bedrooms',
        ),
    ]
